feat: add selector proxy type support

diff --git a/podkop/files/usr/bin/podkop b/podkop/files/usr/bin/podkop
--- a/podkop/files/usr/bin/podkop
+++ b/podkop/files/usr/bin/podkop
@@ -78,7 +78,7 @@ check_requirements() {
     if has_outbound_section; then
         log "Outbound section found" "debug"
     else
-        log "Outbound section not found. Please check your configuration file (missing proxy_string, interface, outbound_json, or urltest_proxy_links). Aborted." "error"
+        log "Outbound section not found. Please check your configuration file (missing proxy_string, selector_proxy_links, urltest_proxy_links, outbound_json, or interface). Aborted." "error"
         exit 1
     fi
 }
@@ -88,12 +88,13 @@ _check_outbound_section() {
     local proxy_string interface outbound_json urltest_proxy_links
 
     config_get proxy_string "$section" "proxy_string"
-    config_get interface "$section" "interface"
-    config_get outbound_json "$section" "outbound_json"
+    config_get selector_proxy_links "$section" "selector_proxy_links"
     config_get urltest_proxy_links "$section" "urltest_proxy_links"
+    config_get outbound_json "$section" "outbound_json"
+    config_get interface "$section" "interface"
 
-    if [ -n "$proxy_string" ] || [ -n "$interface" ] ||
-        [ -n "$outbound_json" ] || [ -n "$urltest_proxy_links" ]; then
+    if [ -n "$proxy_string" ] || [ -n "$selector_proxy_links" ] || [ -n "$urltest_proxy_links" ] ||
+        [ -n "$outbound_json" ] || [ -n "$interface" ]; then
         section_exists=0
     fi
 }
@@ -644,6 +645,35 @@ configure_outbound_handler() {
             local json_outbound
             config_get json_outbound "$section" "outbound_json"
             config=$(sing_box_cf_add_json_outbound "$config" "$section" "$json_outbound")
+            ;;
+        selector)
+            log "Detected proxy configuration type: selector" "debug"
+            local selector_proxy_links udp_over_tcp i outbound_tags outbound_tag default_outbound
+            config_get selector_proxy_links "$section" "selector_proxy_links"
+            config_get udp_over_tcp "$section" "enable_udp_over_tcp"
+
+            if [ -z "$selector_proxy_links" ]; then
+                log "URLTest proxy links is not set. Aborted." "fatal"
+                exit 1
+            fi
+
+            i=1
+            for link in $selector_proxy_links; do
+                config="$(sing_box_cf_add_proxy_outbound "$config" "$section-$i" "$link" "$udp_over_tcp")"
+                outbound_tag="$(get_outbound_tag_by_section "$section-$i")"
+                if [ -z "$outbound_tags" ]; then
+                    outbound_tags="$outbound_tag"
+                    default_outbound="$outbound_tag"
+                else
+                    outbound_tags="$outbound_tags,$outbound_tag"
+                fi
+                i=$((i + 1))
+            done
+
+            selector_tag="$(get_outbound_tag_by_section "$section")"
+            selector_outbounds="$(comma_string_to_json_array "$outbound_tags")"
+            config="$(sing_box_cm_add_selector_outbound "$config" "$selector_tag" "$selector_outbounds" \
+                "$default_outbound")"
             ;;
         urltest)
             log "Detected proxy configuration type: urltest" "debug"
